/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.cpm.guides.guideItem'

export { $nsid }

type Main = {
  $type: 'com.cpm.guides.guideItem'
  guideRef: string
  type: 'article' | 'event' | 'business'
  sourceId?: string
  sourceUrl?: string
  sourceLabel?: string
  title?: string
  description?: string
  snapshotAt?: l.DatetimeString
  createdAt: l.DatetimeString
  updatedAt: l.DatetimeString
}

export type { Main }

const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    guideRef: l.string(),
    type: l.enum(['article', 'event', 'business']),
    sourceId: l.optional(l.string()),
    sourceUrl: l.optional(l.string()),
    sourceLabel: l.optional(l.string()),
    title: l.optional(l.string()),
    description: l.optional(l.string()),
    snapshotAt: l.optional(l.string({ format: 'datetime' })),
    createdAt: l.string({ format: 'datetime' }),
    updatedAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
